version: '3'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "49070:49070"
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - HOST=0.0.0.0
      - PORT=49070
    command: ["./wait-for-it.sh", "mongo:27017", "--", "nodemon", "server"]

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - mongo:/data/db

volumes:
  mongo:
